/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppData, CustomPreset, Subject } from '../types';
import { getLocalDateString } from './date';

export interface ValidationResult {
  success: boolean;
  type?: 'course_design' | 'full_backup';
  data?: AppData;
  error?: string;
}

const VALID_REPEAT_DAYS = new Set(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']);
const HEX_COLOR = /^#[0-9a-fA-F]{6}$/;

export function validateAndParseImport(jsonString: string): ValidationResult {
  if (!jsonString || !jsonString.trim()) {
    return { success: false, error: 'Empty import content.' };
  }

  let parsed: any;
  try {
    parsed = JSON.parse(jsonString);
  } catch (e: any) {
    return {
      success: false,
      error: `Malformed JSON string: ${e.message || 'Syntax Error'}. Please check for missing commas or quotes.`,
    };
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return { success: false, error: 'Invalid JSON format. Expected a JSON object at the root level.' };
  }

  if (parsed.schemaVersion !== undefined) {
    const version = Number(parsed.schemaVersion);
    if (Number.isNaN(version)) {
      return { success: false, error: 'Invalid schemaVersion: must be a number.' };
    }
    if (version > 1) {
      return {
        success: false,
        error: `Unsupported schema version (${version}). This backup/design was generated by a newer version of the app.`,
      };
    }
  }

  const entryMap = parsed.items ?? parsed.subjects;
  const entryLabel = parsed.items ? 'item' : 'subject';
  const entryCollectionLabel = parsed.items ? 'items' : 'subjects';

  if (!entryMap || typeof entryMap !== 'object' || Array.isArray(entryMap)) {
    return { success: false, error: 'Missing or invalid "items" field. Expected a dictionary/object. Old "subjects" templates are still supported.' };
  }

  const subjectsKeys = Object.keys(entryMap);
  if (subjectsKeys.length === 0) {
    return { success: false, error: `The imported template has no ${entryCollectionLabel} configured.` };
  }

  let hasBacklogField = false;
  const validatedSubjects: Record<string, Subject> = {};

  for (const name of subjectsKeys) {
    const trimmedName = name.trim();
    if (!trimmedName) {
      return { success: false, error: 'Entry names cannot be empty.' };
    }

    const sub = entryMap[name];
    if (typeof sub !== 'object' || sub === null) {
      return { success: false, error: `The ${entryLabel} "${trimmedName}" is invalid. Expected an object.` };
    }

    let emoji = '📚';
    if (sub.emoji !== undefined) {
      if (typeof sub.emoji !== 'string') {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid emoji. Expected a string.` };
      }
      emoji = sub.emoji.trim() || '📚';
      if (emoji.length > 15) {
        emoji = emoji.substring(0, 15);
      }
    }

    let color = '#ba68c8';
    if (sub.color !== undefined) {
      if (typeof sub.color !== 'string') {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid color code. Expected a string.` };
      }
      color = sub.color.trim() || '#ba68c8';
      if (!HEX_COLOR.test(color)) {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid color code. Use a six-digit hex color such as #6750a4.` };
      }
    }

    let perday_type: string | undefined;
    if (sub.perday_type !== undefined) {
      if (typeof sub.perday_type !== 'string') {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid perday_type. Expected a string.` };
      }
      perday_type = sub.perday_type.trim().slice(0, 32) || undefined;
    }

    let repeat_days: string[] | undefined;
    if (sub.repeat_days !== undefined) {
      if (!Array.isArray(sub.repeat_days)) {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has invalid repeat_days. Expected an array.` };
      }
      const normalizedDays = sub.repeat_days.map((day: unknown) => typeof day === 'string' ? day.toLowerCase().trim() : '');
      const invalidDay = normalizedDays.find((day: string) => !VALID_REPEAT_DAYS.has(day));
      if (invalidDay !== undefined) {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has invalid repeat_days. Use mon, tue, wed, thu, fri, sat, or sun.` };
      }
      repeat_days = Array.from(new Set(normalizedDays));
    }

    const hasExplicitPerday = sub.perday !== undefined || sub.daily_increase !== undefined;
    const hasRepeatDays = Boolean(repeat_days?.length);
    let growth_mode: Subject['growth_mode'] = 'none';
    if (sub.growth_mode !== undefined) {
      if (sub.growth_mode === 'none' || sub.growth_mode === 'perday' || sub.growth_mode === 'repeat') {
        growth_mode = sub.growth_mode;
      } else {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid growth_mode.` };
      }
    } else {
      growth_mode = hasExplicitPerday ? 'perday' : hasRepeatDays ? 'repeat' : 'none';
    }

    let daily_increase = (growth_mode === 'repeat' || growth_mode === 'perday') ? 1 : 0;
    if (hasExplicitPerday) {
      const parsedGrowth = Number(sub.perday ?? sub.daily_increase);
      if (!Number.isFinite(parsedGrowth) || parsedGrowth < 0) {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid perday value. Must be a non-negative number.` };
      }
      daily_increase = parsedGrowth;
    }

    let completion_mode: 'todo' | 'backlog' = 'backlog';
    if (sub.completion_mode !== undefined) {
      if (sub.completion_mode === 'todo' || sub.completion_mode === 'backlog') {
        completion_mode = sub.completion_mode;
      } else {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid completion_mode. Expected "todo" or "backlog".` };
      }
    }

    let backlog = 0;
    if (sub.backlog !== undefined) {
      hasBacklogField = true;
      const parsedBacklog = Number(sub.backlog);
      if (!Number.isFinite(parsedBacklog) || parsedBacklog < 0) {
        return { success: false, error: `The ${entryLabel} "${trimmedName}" has an invalid backlog value. Must be a non-negative number.` };
      }
      backlog = parsedBacklog;
    }

    if (completion_mode === 'todo') {
      if (sub.backlog !== undefined) {
        backlog = Math.max(0, Math.min(1, backlog));
      } else {
        backlog = 1;
      }
    }

    validatedSubjects[trimmedName] = {
      name: trimmedName,
      emoji,
      color,
      daily_increase,
      backlog,
      perday_type,
      repeat_days,
      growth_mode,
      completion_mode,
      schedule_conflict: sub.growth_mode === undefined && hasExplicitPerday && hasRepeatDays,
    };
  }

  const isFullBackup = hasBacklogField || parsed.last_updated !== undefined || parsed.setup_done !== undefined;
  const exportType = isFullBackup ? 'full_backup' : 'course_design';

  const courseName = typeof parsed.title === 'string' && parsed.title.trim()
    ? parsed.title.trim()
    : typeof parsed.course_name === 'string' && parsed.course_name.trim()
    ? parsed.course_name.trim()
    : (typeof parsed.title === 'string' && parsed.title.trim() ? parsed.title.trim() : 'Imported Course');

  let classesPerDay = 4;
  if (parsed.classes_per_day !== undefined) {
    const parsedClassesPerDay = Number(parsed.classes_per_day);
    if (!Number.isFinite(parsedClassesPerDay) || parsedClassesPerDay < 1) {
      return { success: false, error: 'classes_per_day must be a finite number of at least 1.' };
    }
    classesPerDay = Math.floor(parsedClassesPerDay);
  }

  const skipSunday = parsed.skip_sunday !== undefined
    ? Boolean(parsed.skip_sunday)
    : true;

  const theme = parsed.theme === 'light' || parsed.theme === 'dark'
    ? parsed.theme
    : 'dark';

  if (parsed.palette_color !== undefined && (typeof parsed.palette_color !== 'string' || !HEX_COLOR.test(parsed.palette_color))) {
    return { success: false, error: 'palette_color must be a six-digit hex color such as #6750a4.' };
  }
  const palette_color = parsed.palette_color as string | undefined;

  const lastUpdated = typeof parsed.last_updated === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(parsed.last_updated)
    ? parsed.last_updated
    : getLocalDateString();

  const cleanData: AppData = {
    subjects: validatedSubjects,
    classes_per_day: classesPerDay,
    skip_sunday: skipSunday,
    course_name: courseName,
    last_updated: lastUpdated,
    setup_done: isFullBackup ? (parsed.setup_done !== undefined ? Boolean(parsed.setup_done) : true) : false,
    theme: theme,
    palette_color: palette_color,
    auto_growth_enabled: parsed.auto_growth_enabled !== undefined ? Boolean(parsed.auto_growth_enabled) : true,
  };

  if (parsed.custom_presets !== undefined) {
    if (!Array.isArray(parsed.custom_presets)) {
      return { success: false, error: 'Invalid custom_presets. Expected an array.' };
    }
    const presetIds = new Set<string>();
    const presets: CustomPreset[] = [];
    for (const rawPreset of parsed.custom_presets) {
      if (!rawPreset || typeof rawPreset !== 'object' || Array.isArray(rawPreset)) {
        return { success: false, error: 'A custom preset is invalid.' };
      }
      const preset = rawPreset as Partial<CustomPreset>;
      const id = typeof preset.id === 'string' ? preset.id.trim() : '';
      const name = typeof preset.name === 'string' ? preset.name.trim() : '';
      if (!id || !name || presetIds.has(id) || !Array.isArray(preset.entries)) {
        return { success: false, error: 'A custom preset is missing a unique id, name, or entries list.' };
      }
      presetIds.add(id);
      const entries = preset.entries.filter((entry): entry is Subject => {
        return Boolean(entry) && typeof entry.name === 'string' && entry.name.trim().length > 0 &&
          typeof entry.emoji === 'string' && typeof entry.color === 'string' && HEX_COLOR.test(entry.color) &&
          Number.isFinite(entry.backlog) && entry.backlog >= 0 && Number.isFinite(entry.daily_increase) && entry.daily_increase >= 0;
      }).map(entry => ({
        ...entry,
        name: entry.name.trim(),
        emoji: entry.emoji.trim() || '📚',
        repeat_days: entry.repeat_days?.filter(day => VALID_REPEAT_DAYS.has(day))
      }));
      if (entries.length !== preset.entries.length) {
        return { success: false, error: `Custom preset "${name}" contains an invalid entry.` };
      }
      presets.push({ id, name, emoji: typeof preset.emoji === 'string' && preset.emoji.trim() ? preset.emoji.trim() : '✨', entries });
    }
    cleanData.custom_presets = presets;
  }

  if (parsed.preset_overrides !== undefined) {
    if (!parsed.preset_overrides || typeof parsed.preset_overrides !== 'object' || Array.isArray(parsed.preset_overrides)) {
      return { success: false, error: 'Invalid preset_overrides. Expected an object.' };
    }
    const overrides: Record<string, Subject[]> = {};
    for (const [key, rawEntries] of Object.entries(parsed.preset_overrides)) {
      if (!Array.isArray(rawEntries)) {
        return { success: false, error: `Preset override "${key}" must contain an entries list.` };
      }
      const entries = rawEntries.filter((entry): entry is Subject => {
        return Boolean(entry) && typeof entry === 'object' && typeof entry.name === 'string' && entry.name.trim().length > 0 &&
          typeof entry.emoji === 'string' && typeof entry.color === 'string' && HEX_COLOR.test(entry.color) &&
          Number.isFinite(entry.backlog) && entry.backlog >= 0 && Number.isFinite(entry.daily_increase) && entry.daily_increase >= 0;
      }).map(entry => ({
        ...entry,
        name: entry.name.trim(),
        emoji: entry.emoji.trim() || '📚',
        repeat_days: entry.repeat_days?.filter(day => VALID_REPEAT_DAYS.has(day))
      }));
      if (entries.length !== rawEntries.length) {
        return { success: false, error: `Preset override "${key}" contains an invalid entry.` };
      }
      overrides[key] = entries;
    }
    cleanData.preset_overrides = overrides;
  }

  if (!isFullBackup) {
    Object.keys(cleanData.subjects).forEach(key => {
      cleanData.subjects[key].backlog = cleanData.subjects[key].completion_mode === 'todo' ? 1 : 0;
    });
  }

  return {
    success: true,
    type: exportType,
    data: cleanData,
  };
}
